logging:
  level:
    my.restaurant: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myopenrestaurant
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:changelog/main.xml
    enabled: true